name: Build and Run Juice Shop with Docker, Generate SBOM, SAST, and Gitleaks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t juice-shop .

    - name: Run Juice Shop container
      run: |
        docker run -d -p 3000:3000 --name juice-shop-container juice-shop

    - name: Check if Juice Shop is running
      run: |
        sleep 10
        curl --fail http://localhost:3000 || exit 1

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM as JSON with Syft
      run: |
        syft juice-shop -o json > sbom.json

    - name: Display SBOM JSON output
      run: |
        cat sbom.json

    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-json
        path: sbom.json

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep Scan (SARIF)
      run: |
        semgrep --config auto --sarif --output semgrep-results.sarif

    - name: Upload Semgrep Results (SARIF)
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sarif-results
        path: semgrep-results.sarif

    - name: Run Gitleaks Scan Using Docker Image
      run: |
        docker run --rm -v $(pwd):/project --workdir /project zricethezav/gitleaks:latest detect --source . --report-format json --report-path gitleaks-results.json
      continue-on-error: true  # Hata durumunda bile pipeline devam edecek

    - name: Upload Gitleaks Results
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-results
        path: gitleaks-results.json
